### ISSUE TITLE
Compile and run Errors

### ISSUE THREAD

**Issue by idealgao** [sangjae4309/gem5_ramulator2#1]
Hi,

I fully clone this repository, but the compile comes out syntax error, for example:
 
ramulator2.cc line 183:
receive_external_requests(0, pkt->getAddr(), 0    -> receive_external_requests(0, pkt->getAddr(), 0 **,**

And dockerfile seem not work well neither.
RUN git clone https://github.com/CMU-SAFARI/ramulator2.git /root/gem5-ramulator2/gem5/ext/ramulator/ramulator2
-> RUN git clone https://github.com/CMU-SAFARI/ramulator2.git /root/gem5-ramulator2/gem5/ext/ramulator**2**/ramulator2

Could you  kindly clone this repository and fix these bugs? And a self-test sample cmd will be thanksful.
command line: build/X86/gem5.opt configs/deprecated/example/se.py --cmd=tests/test-progs/hello/bin/x86/linux/hello --cpu-type=TimingSimpleCPU --l1d_size=64kB --l1i_size=16kB --caches --mem-type=Ramulator2

**Comment by sangjae4309** [comment]
Hi idealgao

First of all, thank you for reporting me a bug.

I found some bug on docker files and updated the guideline.

please check again.
